version: '3'
services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:80" # FastAPIアプリケーションのデフォルトポートは8000。外部からは80ポートでアクセスできるようにする
    volumes:
      - ./app:/app # ホストのappディレクトリをコンテナの/appディレクトリにマウント
  front:
    build:
      context: ./front/quasar-app
      dockerfile: Dockerfile
    ports:
      - "8090:80" # Nginxを外部からアクセス可能にする
    environment:
      - PRINT_SERVER_URL=http://server:8000    
    volumes:
      - ./front/quasar-app/dist/spa:/usr/share/nginx/html # ホストのfront/srcディレクトリをコンテナの/usr/share/nginx/htmlディレクトリにマウント
