"""first

Revision ID: 283c63455579
Revises: 8f99d63357b8
Create Date: 2022-10-01 17:12:15.905357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283c63455579'
down_revision = '8f99d63357b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
