"""first

Revision ID: 90fd66b10fb7
Revises: 9f59f7e35e5a
Create Date: 2022-10-01 15:47:19.988168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fd66b10fb7'
down_revision = '9f59f7e35e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
